# mdcr_enroll_ab_33 <- readr::read_rds(here::here("data", "mdcr_enroll_ab_33.rds"))
# mdcr_enroll_ab_34 <- readr::read_rds(here::here("data", "mdcr_enroll_ab_34.rds"))
# mdcr_enroll_ab_35 <- readr::read_rds(here::here("data", "mdcr_enroll_ab_35.rds"))
# mdcr_enroll_ab_36 <- readr::read_rds(here::here("data", "mdcr_enroll_ab_36.rds"))
# mdcr_enroll_ab_37 <- readr::read_rds(here::here("data", "mdcr_enroll_ab_37.rds"))
# mdcr_enroll_ab_38 <- readr::read_rds(here::here("data", "mdcr_enroll_ab_38.rds"))
# mdcr_enroll_ab_39 <- readr::read_rds(here::here("data", "mdcr_enroll_ab_39.rds"))

enroll_33 <- readr::read_rds(here::here("data", "clean", "enroll_clean_33.rds"))
enroll_34 <- readr::read_rds(here::here("data", "clean", "enroll_clean_34.rds"))
enroll_35 <- readr::read_rds(here::here("data", "clean", "enroll_clean_35.rds"))
enroll_36 <- readr::read_rds(here::here("data", "clean", "enroll_clean_36.rds"))
enroll_37 <- readr::read_rds(here::here("data", "clean", "enroll_clean_37.rds"))
enroll_38 <- readr::read_rds(here::here("data", "clean", "enroll_clean_38.rds"))
enroll_39 <- readr::read_rds(here::here("data", "clean", "enroll_clean_39.rds"))