# mdcr_enroll_ab_3 <- readr::read_rds(here::here("data", "mdcr_enroll_ab_3.rds"))
# mdcr_enroll_ab_4 <- readr::read_rds(here::here("data", "mdcr_enroll_ab_4.rds"))
# mdcr_enroll_ab_5 <- readr::read_rds(here::here("data", "mdcr_enroll_ab_5.rds"))
# mdcr_enroll_ab_6 <- readr::read_rds(here::here("data", "mdcr_enroll_ab_6.rds"))
# mdcr_enroll_ab_7 <- readr::read_rds(here::here("data", "mdcr_enroll_ab_7.rds"))
# mdcr_enroll_ab_8 <- readr::read_rds(here::here("data", "mdcr_enroll_ab_8.rds"))

enroll_3 <- readr::read_rds(here::here("data", "clean", "enroll_clean_3.rds"))
enroll_4 <- readr::read_rds(here::here("data", "clean", "enroll_clean_4.rds"))
enroll_5 <- readr::read_rds(here::here("data", "clean", "enroll_clean_5.rds"))
enroll_6 <- readr::read_rds(here::here("data", "clean", "enroll_clean_6.rds"))
enroll_7 <- readr::read_rds(here::here("data", "clean", "enroll_clean_7.rds"))
enroll_8 <- readr::read_rds(here::here("data", "clean", "enroll_clean_8.rds"))